### PR TITLE
Generate Reusable enumeration in controller ...

### LINKED ISSUE #5: UITableViewCell/UICollectionViewCell Reuse Identifiers
Another thing that would be nice to have statically typed is tableView/collectionView reuse identifiers.

### PR DESCRIPTION
**Pull request by phimage**
...with UITableViewCell/UICollectionViewCell reuse identifiers - Fix #5 
Add method to use the Reusable enumerations to dequeue or register view

add info in REAME.md, less than previous PR

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
@phimage please review the changes here. there is conflict due to another PR merged already.

**Comment by phimage** [comment]
conflict resolved

**Comment by krzyzanowskim** [comment]
damn, again need coreection to be merged :-)

**Comment by krzyzanowskim** [comment]
@phimage

**Comment by phimage** [comment]
Is it good?
no conflict when I merged this time

**Comment by krzyzanowskim** [comment]
yeap, thx

**Pull request merged**
