### PR TITLE
Modify whitespace

### PR DESCRIPTION
**Pull request by a2**
The trailing whitespace removal makes this hard to review. Sorry! :grin:

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
why not update do i need separated PR for that?

**Comment by a2** [comment]
This has other whitespace tweaks that weren't in the other diff.

**Comment by krzyzanowskim** [comment]
"We can’t automatically merge this pull request." HAHAHA 😂

**Comment by a2** [comment]
Updated! :smile:

**Pull request merged**
